from data_collection import *
from time import sleep
import os

famous_people = [
    "Taylor Swift",
    "Justin Bieber",
    "Katy Perry",
    "Beyonce",
    "Lady Gaga",
    "Miley Cyrus",
    "Kanye West",
    "Kendrick Lamar",
    "Obama",
    "Kim Kardashian",
    "Selena Gomez",
    "Ariana Grande",
    "Ellen DeGeneres",
    "Chris Brown",
    "Drake",
    "Nicki Minaj",
    "Kylie Jenner",
    "Kourtney Kardashian",
    "Khloe Kardashian",
    "Robert Downey Jr.",
    "Chris Pratt",
    "Chris Evans",
    "Scarlett Johansson",
    "Chris Hemsworth",
    "Mark Ruffalo",
    "Tom Holland",
    "Tom Hiddleston",
    "Benedict Cumberbatch",
    "Arnold Schwarzenegger",
    "Dwayne Johnson",
    "Vin Diesel",
    "Jason Statham",
    "Will Smith",
    "Tom Cruise",
    "Brad Pitt",
    "Leonardo DiCaprio",
    "Jennifer Lawrence",
    "Emma Stone",
    "Megan Fox",
    "Angelina Jolie",
    "Halle Berry",
    "Jennifer Aniston",
    "Shakira",
    "Paul Rudd",
    "Ryan Reynolds",
    "Chris Pine",
    "Elton John",
    "Bono",
    "Bruce Springsteen",
    "Bob Dylan",
    "David Bowie",
    "Elon Musk",
    "Bill Gates",
    "Mark Zuckerberg",
    "Jeff Bezos",
    "Michelle Obama",
    "Hillary Clinton",
    "George W. Bush",
    "Bill Clinton",
    "Cristiano Ronaldo",
    "Lionel Messi",
    "Neymar",
    "Zlatan Ibrahimovic",
    "Bradley Cooper",
    "Ryan Gosling",
    "Adam Sandler",
    "Adam Levine",
    "Zac Efron",
    "Bryan Cranston",
    "Aaron Paul",
    "Jesse Eisenberg",
    "Jared Leto",
    "Joaquin Phoenix",
    "Christian Bale",
    "Johnny Depp",
    "Tom Hardy",
    "Will Ferrell",
    "Steve Carell",
    "Channing Tatum",
    "Matthew McConaughey",
    "Sandra Bullock",
    "Julia Roberts",
    "Meryl Streep",
    "Emma Watson",
    "Jennifer Lopez",
    "Cameron Diaz",
    "Demi Lovato",
    "Britney Spears",
    "Adele",
    "Ed Sheeran",
    "Justin Timberlake",
    "Bruno Mars",
    "George Clooney",
    "Matt Damon",
    "Ben Affleck",
    "Matt LeBlanc",
    "David Schwimmer",
    "Courteney Cox",
    "Jennifer Aniston",
    "Matthew Perry",
    "Lisa Kudrow",
    "Kaley Cuoco",
    "Jim Parsons",
    "Johnny Galecki",
    "Simon Cowell",
    "Ryan Seacrest",
    "Jimmy Fallon",
    "Jimmy Kimmel",
    "Stephen Colbert",
    "James Corden",
    "Seth Meyers",
    "Seth MacFarlane",
    "Seth Rogen",
    "James Franco",
    "Jonah Hill",
    "Dakota Johnson",
    "Jamie Dornan",
    "Channing Tatum",
    "Jamie Foxx",
    "Will Smith",
    "Kevin Hart",
    "Hugh Jackman",
    "Grant Gustin",
    "Stephen Amell",
    "Tom Ellis",
    "Jensen Ackles",
    "Jared Padalecki",
    "Misha Collins",
    "Lin-Manuel Miranda",
    "Donald Glover",
    "John Legend",
    "Idris Elba",
    "Michael B. Jordan",
    "Serena Williams",
    "Mackenzie Scott",
    "Maria Sharapova",
    "Serena Williams",
    "Rafael Nadal",
    "Roger Federer",
    "Melinda Gates",
    "Kamala Harris",
    "Michelle Obama",
    "AOC",
    "Abigail Johnson",
    "Greta Thunberg",
    "Nancy Pelosi",
    "Sophia Vergara",
    "Margot Robbie",
    "Jessica Chastain",
    "Jennifer Garner",
    "Kate Hudson",
    "Kate Middleton",
    "Prince William",
    "Prince Harry",
    "Jennifer Lawrence",
    "Elizabeth Olsen",
    "Scarlett Johansson",
    "Emma Stone",
    "Megan Fox",
    "Kim Kardashian",
    "Sarah Jessica Parker",
    "Saoirse Ronan",
    "Michelle Yeoh",
    "Zoe Saldana",
    "Gal Gadot",
    "Brie Larson",
    "Zoe Kravitz",
    "Robert Pattinson",
    "Henry Cavill",
    "Sandra Bullock",
    "Reese Witherspoon",
    "Kate Winslet",
    "Julia Roberts",
    "Meryl Streep",
    "Will Smith",
    "Benedict Cumberbatch",
    "Tom Hanks",
    "Oscar Isaac",
    "Chris Pine",
    "Mads Mikkelsen",
    "Daniel Kaluuya",
    "Pedro Pascal",
    "Michael B. Jordan",
    "Andrew Garfield",
    "Tobey Maguire",
    "Tom Hardy",
    "Tom Holland",
    "Mark Ruffalo",
    "Mark Wahlberg",
    "Jude Law",
    "Remi Malek",
    "Christian Bale",
    "Miles Teller",
    "Gary Oldman",
    "Ben Affleck",
    "Matt Damon",
    "Brad Pitt",
    "Daniel Craig",
    "George Clooney",
    "Danny DeVito",
    "Michael Douglas",
    "Zachary Levi",
    "Zendaya",
    "Serena Williams",
    "Colin Farrell",
    "Michael Fassbender",
    "Michael Shannon",
    "Michael Keaton",
    "Jason Momoa",
    "Jason Statham",
    "Jason Bateman",
    "Jason Sudeikis",
    "Jason Segel",
    "Jason Schwartzman",
    "Jason Isaacs",
    "Jim Carrey",
    "Josh Hutcherson",   
    "Jared Leto",
    "Josh Brolin",
    "Josh Duhamel",
    "Josh Gad",
    "Josh Hartnett",
    "Kevin Bacon",
    "Kevin Costner",
    "Kevin Spacey",
    "Kevin Kline",
    "Kevin James",
    "Kevin Connolly",
    "Jennifer Lawrence",
    "Jennifer Garner",
    "Jennifer Connelly",
    "Gwyneth Paltrow",
    "Gwen Stefani",
    "Giancarlo Esposito",
    "Bob Odinkirk",
    "Jonathan Banks",
    "Jonathan Groff",
    "Seth Meyers",
    "Pete Davidson",
    "Benjamin Netanyahu",
    "David Blaine",
    "David Copperfield",
    "David Spade",
    "David Schwimmer",
    "David Duchovny",
    "David Beckham",
    "David Tennant",
    "David Harbour",
    "Christopher Nolan",
    "Ben Cohen",
    "Anderson Cooper",
    "Anna Kendrick",
    "Anna Gunn",
]

for name in famous_people :
    name = name.lower()
    try :
        if (not json_includes(name, "Webpage/data.json")) : #if data doesn't already exists
            write_data(name)
            print("Successfully fetched data for " + name)
            sleep(2)
        else : #if data already exists
            print("Data already exists for " + name)
    except ValueError :
        print("Error fetching data for " + name)
