from data_collection import *
from time import sleep
import os

famous_people = [
    "1. Barack Obama",
"2. Bill Gates",
"4. Steven Spielberg",
"5. George Clooney",
"6. Beyoncé",
"7. Justin Bieber",
"8. Taylor Swift",
"9. Kanye West",
"10. Lionel Messi",
"11. Cristiano Ronaldo",
"12. LeBron James",
"13. Roger Federer",
"14. Tiger Woods",
"15. Phil Mickelson",
"16. Floyd Mayweather",
"17. Manny Pacquiao",
"18. Serena Williams",
"19. Maria Sharapova",
"20. Rafael Nadal",
"21. Novak Djokovic",
"22. Andy Murray",
"23. Zlatan Ibrahimovic",
"24. Gareth Bale",
"25. Neymar",
"26. Luis Suárez",
"27. Wayne Rooney",
"28. Eden Hazard",
"29. Kevin Durant",
"30. Stephen Curry",
"31. James Harden",
"32. Russell Westbrook",
"33. Kyrie Irving",
"34. Anthony Davis",
"35. Chris Paul",
"36. Kawhi Leonard",
"37. Damian Lillard",
"38. DeMar DeRozan",
"39. Klay Thompson",
"40. Jimmy Butler",
"41. Paul George",
"42. John Wall",
"43. Karl-Anthony Towns",
"44. Kristaps Porzingis",
"45. Joel Embiid",
"46. Giannis Antetokounmpo",
"47. LaMarcus Aldridge",
"48. DeMarcus Cousins",
"49. Draymond Green",
"50. Kyle Lowry",
"51. Kevin Love",
"52. Victor Oladipo",
"53. Blake Griffin",
"54. Al Horford",
"55. Mike Conley",
"56. Kyrie Irving",
"57. Kemba Walker",
"58. Eric Bledsoe",
"59. Russell Westbrook",
"60. DeAndre Jordan",
"63. Rudy Gobert",
"64. Nikola Jokić",
"65. Hassan Whiteside",
"66. Jimmy Butler",
"68. LaMarcus Aldridge",
"69. Carmelo Anthony",
"70. Dwyane Wade",
"71. Chris Paul",
"72. Damian Lillard",
"73. Kyrie Irving",
"74. Klay Thompson",
"75. DeMar DeRozan",
"76. C.J. McCollum",
"77. Kyle Lowry",
"78. Paul George",
"79. Jimmy Butler",
"80. Russell Westbrook",
"2. Bill Gates",
"3. Beyoncé",
"4. George Clooney",
"5. Ellen DeGeneres",
"6. Jimmy Fallon",
"7. Kim Kardashian",
"9. Justin Bieber",
"10. Taylor Swift",
"12. Lionel Messi",
"13. Cristiano Ronaldo",
"14. Neymar",
"15. LeBron James",
"16. Alex Morgan",
"17. Serena Williams",
"18. Kevin Durant",
"19. Stephen Curry",
"20. Usain Bolt",
"21. Roger Federer",
"22. Rafael Nadal",
"23. Novak Djokovic",
"24. Tiger Woods",
"25. Phil Mickelson",
"26. Tom Brady",
"27. Aaron Rodgers",
"28. Russell Wilson",
"29. J.J. Watt",
"30. Alex Ovechkin",
"31. Sidney Crosby",
"32. Connor McDavid",
"33. Carey Price",
"34. Mike Trout",
"35. Clayton Kershaw",
"36. Miguel Cabrera",
"37. Bryce Harper",
"38. Josh Hamilton",
"39. Albert Pujols",
"40. Derek Jeter",
"41. Alex Rodriguez",
"42. Ichiro Suzuki",
"43. David Ortiz",
"44. Manny Machado",
"45. Buster Posey",
"47. Felix Hernandez",
"52. Kris Bryant",
"58. Carlos Correa",
"1. Leonardo DiCaprio",
"2. Tom Hanks",
"3. Meryl Streep",
"4. Jennifer Lawrence",
"5. Johnny Depp",
"6. Brad Pitt",
"7. Angelina Jolie",
"8. Will Smith",
"9. Jennifer Aniston",
"10. Matt Damon",
"11. Julia Roberts",
"12. George Clooney",
"13. Ben Affleck",
"14. Jennifer Lopez",
"15. Denzel Washington",
"16. Viola Davis",
"17. Seth Rogen",
"18. Ryan Reynolds",
"19. Dwayne Johnson",
"20. Chris Pratt",
"21. Mark Wahlberg",
"22. Will Ferrell",
"23. Scarlett Johansson",
"24. Amy Poehler",
"25. Kevin Hart",
"26. Paul Rudd",
"27. Tiffany Haddish",
"28. Steve Carell",
"29. Chris Evans",
"30. Adam Sandler",
"31. Benedict Cumberbatch",
"32. Chadwick Boseman",
"33. Chris Hemsworth",
"34. Chris Pine",
"35. Gal Gadot",
"36. Hugh Jackman",
"37. Jake Gyllenhaal",
"38. Jared Leto",
"39. Jeremy Renner",
"40. Jesse Eisenberg",
"41. Joaquin Phoenix",
"42. John Krasinski",
"43. Josh Brolin",
"44. Justin Timberlake",
"45. Ryan Gosling",
"47. Tom Cruise",
"48. Vin Diesel",
"49. Zach Galifianakis",
"50. Zoe Saldana",
"51. Amy Adams",
"52. Amy Schumer",
"53. Andrew Garfield",
"54. Anne Hathaway",
"55. Brie Larson",
"56. Cameron Diaz",
"57. Channing Tatum",
"58. Charlize Theron",
"59. Daniel Craig",
"60. Danny DeVito",
"61. Dave Bautista",
"62. David Beckham",
"63. David Duchovny",
"64. David Spade",
"65. Dax Shepard",
"66. Drew Barrymore",
"67. Eddie Murphy",
"68. Elijah Wood",
"69. Emma Stone",
"70. Emma Watson",
"71. Evan Peters",
"72. Seth MacFarlane",
"73. Idris Elba",
"74. Jack Black",
"75. James Franco",
"76. Jamie Foxx",
"77. Jason Bateman",
"78. Jason Statham",
"79. Jennifer Garner",
"80. Jessica Chastain",
"81. John Goodman",
"82. John Leguizamo",
"83. John Malkovich",
"84. Jonah Hill",
"85. Joseph Gordon-Levitt",
"86. Josh Hutcherson",
"87. Justin Bieber",
"88. Kate Winslet",
"89. Keanu Reeves",
"90. Kirsten Dunst",
"91. Kit Harington",
"92. Kristen Stewart",
"93. Kylie Jenner",
"94. Lady Gaga",
"95. Leonardo DiCaprio",
"96. Liam Neeson",
"97. Mahershala Ali",
"98. Margot Robbie",
"99. Matt Smith",
"100. Melissa McCarthy",
"101. Michael B. Jordan",
"102. Mindy Kaling",
"103. Naomi Watts",
"104. Natalie Portman",
"105. Neil Patrick Harris",
"106. Nick Jonas",
"107. Nicole Kidman",
"108. Orlando Bloom",
"109. Owen Wilson",
"110. Paul Giamatti",
"111. Penelope Cruz",
"112. Reese Witherspoon",
"113. Robert De Niro",
"114. Robert Downey Jr.",
"115. Roger Federer",
"116. Rooney Mara",
"117. Salma Hayek",
"118. Seth Rogan",
"119. Shailene Woodley",
"120. Shia LaBeouf",
"121. Sophie Turner",
"122. Steve Buscemi",
"123. Steven Spielberg",
"124. Taylor Lautner",
"125. Tina Fey",
"126. Tom Cruise",
"127. Viola Davis",
"128. Will Smith",
"129. Zac Efron",
"130. Zooey Deschanel",
"131. Amy Poehler",
"132. Angelina Jolie",
"133. Bette Midler",
"134. Beyonce",
"135. Bill Murray",
"136. Billy Crystal",
"137. Brad Pitt",
"138. Cameron Diaz",
"139. Carey Mulligan",
"140. Carrie Underwood",
"141. Celine Dion",
"142. Channing Tatum",
"143. Charlize Theron",
"144. Christina Aguilera",
"145. Clint Eastwood",
"146. Daniel Radcliffe",
"147. Dolly Parton",
"148. Drew Barrymore",
"149. Eddie Murphy",
"150. Ellen DeGeneres",
"151. Elton John",
"152. Eminem",
"153. Jennifer Aniston",
"154. Jennifer Lopez",
"155. Jessica Simpson",
"156. Jim Carrey",
"157. Jimmy Fallon",
"158. Joan Rivers",
"159. Joe Manganiello",
"160. John Goodman",
"161. Johnny Depp",
"162. Justin Bieber",
"163. Justin Timberlake",
"164. Katie Holmes",
"165. Kelly Clarkson",
"166. Kevin Bacon",
"167. Kevin Costner",
"168. Kristin Chenoweth",
"169. Kylie Jenner",
"170. Lady Gaga",
"171. Leonardo Dicaprio",
"172. LL Cool J",
"173. Madonna",
"174. Matthew McConaughey",
"175. Melissa McCarthy",
"176. Miley Cyrus",
"177. Morgan Freeman",
"178. Naomi Watts",
"179. Natalie Portman",
"180. Neil Patrick Harris",
"181. Nicki Minaj",
"182. Nicole Kidman",
"184. Reese Witherspoon",
"186. Robert De Niro",
"188. Sandra Bullock",
"189. Scarlett Johansson",
"190. Sean Connery",
"191. Seth Rogen",
"192. Taylor Swift",
"193. The Rock",
"194. Tom Cruise",
"195. Tom Hanks",
"196. Tyler Perry",
"197. Will Ferrell",
"198. Will Smith",
"199. Zac Efron",
"200. Zooey Deschanel",
"201. Adam Levine",
"202. Adele",
"203. Amy Schumer",
"204. Beyonce",
"205. Blake Shelton",
"206. Bruno Mars",
"207. Carrie Underwood",
"208. Channing Tatum",
"209. Christina Aguilera",
"210. Daniel Craig",
"211. Dwayne Johnson",
"212. Jennifer Lawrence",
"213. Jennifer Lopez",
"214. Jessica Simpson",
"215. Justin Bieber",
"216. Justin Timberlake",
"217. Kanye West",
"218. Kelly Clarkson",
"219. Kevin Hart",
"220. Kylie Jenner",
"221. Lady Gaga",
"222. Leonard DiCaprio",
"223. Miley Cyrus",
"224. Naomi Watts",
"225. Natalie Portman",
"226. Nicki Minaj",
"228. Reese Witherspoon",
"230. Robert Downey Jr.",
"232. Sandra Bullock",
"233. Scarlett Johansson",
"234. Sean Connery",
"235. Seth Rogen",
"236. Taylor Swift",
"237. The Rock",
"238. Tom Cruise",
"239. Tom Hanks",
"240. Tyler Perry",
"241. Will Ferrell",
"242. Will Smith",
"243. Zac Efron",
"244. Zooey Deschanel",
"245. Jennifer Aniston",
"246. Jennifer Lawrence",
"247. Jessica Alba",
"248. Jessica Simpson",
"249. Justin Bieber",
"250. Justin Timberlake",
"251. Kendall Jenner",
"252. Kim Kardashian",
"253. Kylie Jenner",
"254. Lady Gaga",
"255. Leonardo DiCaprio",
"256. Lindsey Vonn",
"257. Madonna",
"258. Mariah Carey",
"259. Megan Fox",
"261. Michelle Obama",
"262. Miley Cyrus",
"263. Naomi Campbell",
"264. Naomi Watts",
"265. Natalie Portman",
"266. Neymar",
"267. Nicki Minaj",
"269. Peyton Manning",
"270. Rafael Nadal",
"271. Reese Witherspoon",
"273. Robert De Niro",
"274. Roger Federer",
"275. Ronaldo",
"276. Russell Westbrook",
"277. Ryan Gosling",
"278. Selena Gomez",
"279. Serena Williams",
"280. Shah Rukh Khan",
"281. Taylor Swift",
"282. Tiger Woods",
"283. Tom Brady",
"284. Tom Cruise",
"285. Tyler Perry",
"286. Venus Williams",
"287. Victoria Beckham",
"288. Virat Kohli",
"289. Will Smith",
"290. Yao Ming",
"291. Zachary Levi",
"292. Zooey Deschanel",
"293. Amy Poehler",
"294. Angelina Jolie",
"295. Beyonce",
"296. Brad Pitt",
"297. Cameron Diaz",
"298. Carey Mulligan",
"299. Carrie Underwood",
"300. Celine Dion",
"301. Channing Tatum",
"302. Charlize Theron",
"303. Christina Aguilera",
"304. Daniel Radcliffe",
"305. Dolly Parton",
"306. Drew Barrymore",
"307. Eddie Murphy",
"308. Ellen DeGeneres",
"309. Elton John",
"310. Eminem",
"311. Jennifer Aniston",
"312. Jennifer Lopez",
"313. Jessica Simpson",
"314. Jim Carrey",
"315. Jimmy Fallon",
"316. Joan Rivers",
"317. Joe Manganiello",
"318. John Goodman",
"319. Johnny Depp",
"320. Justin Bieber",
"321. Justin Timberlake",
"322. Katie Holmes",
"323. Kelly Clarkson",
"324. Kevin Bacon",
"325. Kevin Costner",
"326. Kristin Chenoweth",
"327. Kylie Jenner",
"328. Lady Gaga",
"329. Leonardo Dicaprio",
"330. LL Cool J",
"331. Madonna",
"332. Matthew McConaughey",
"333. Melissa McCarthy",
"334. Miley Cyrus",
"335. Morgan Freeman",
"336. Naomi Watts",
"337. Natalie Portman",
"338. Neil Patrick Harris",
"339. Nicki Minaj",
"340. Nicole Kidman",
"342. Reese Witherspoon",
"344. Robert De Niro",
"346. Sandra Bullock",
"347. Scarlett Johansson",
"348. Sean Connery",
"349. Seth Rogen",
"350. Taylor Swift",
"351. The Rock",
"352. Tom Cruise",
"353. Tom Hanks",
"354. Tyler Perry",
"355. Will Ferrell",
"356. Will Smith",
"357. Zac Efron",
"358. Zooey Deschanel",
"359. Amy Poehler",
"360. Angelina Jolie",
"361. Bette Midler",
"362. Beyonce",
"363. Bill Murray",
"364. Billy Crystal",
"365. Brad Pitt",
"366. Cameron Diaz",
"367. Carey Mulligan",
"368. Carrie Underwood",
"369. Celine Dion",
"370. Channing Tatum",
"371. Charlize Theron",
"372. Christina Aguilera",
"373. Daniel Craig",
"374. Danny DeVito",
"375. Dave Bautista",
"376. David Beckham",
"377. David Duchovny",
"378. David Spade",
"379. Dax Shepard",
"380. Drew Barrymore",
"381. Eddie Murphy",
"382. Elijah Wood",
"383. Emma Stone",
"384. Emma Watson",
"385. Evan Peters",
"386. Seth MacFarlane",
"387. Idris Elba",
"388. Jack Black",
"389. James Franco",
"390. Jamie Foxx",
"391. Jason Bateman",
"392. Jason Statham",
"393. Jennifer Garner",
"394. Jennifer Lawrence",
"395. Jessica Chastain",
"396. John Goodman",
"397. John Leguizamo",
"398. John Malkovich",
"399. Jonah Hill",
"400. Joseph Gordon-Levitt",
"401. Josh Hutcherson",
"402. Justin Bieber",
"403. Justin Timberlake",
"404. Kate Winslet",
"405. Keanu Reeves",
"406. Kirsten Dunst",
"407. Kit Harington",
"408. Kristen Stewart",
"409. Kylie Jenner",
"410. Lady Gaga",
"411. Leonardo DiCaprio",
"412. Liam Neeson",
"413. Mahershala Ali",
"414. Margot Robbie",
"415. Matt Smith",
"416. Melissa McCarthy",
"417. Michael B. Jordan",
"418. Mindy Kaling",
"419. Naomi Watts",
"420. Natalie Portman",
"421. Neil Patrick Harris",
"422. Nick Jonas",
"423. Nicole Kidman",
"424. Orlando Bloom",
"425. Owen Wilson",
"426. Paul Giamatti",
"427. Penelope Cruz",
"428. Reese Witherspoon",
"429. Robert De Niro",
"430. Robert Downey Jr.",
"431. Roger Federer",
"432. Rooney Mara",
"433. Salma Hayek",
"434. Seth Rogan",
"435. Shia LaBeouf",
"436. Sophie Turner",
"437. Steve Buscemi",
"438. Steven Spielberg",
"439. Taylor Lautner",
"440. Tina Fey",
"441. Tom Cruise",
"442. Viola Davis",
"443. Will Smith",
"444. Zac Efron",
"445. Zooey Deschanel",
"446. Amy Schumer",
"447. Andrew Garfield",
"448. Anne Hathaway",
"449. Brie Larson",
"450. Cameron Diaz",
"451. Channing Tatum",
"452. Charlize Theron",
"453. Daniel Craig",
"454. Danny DeVito",
"455. Dave Bautista",
"456. David Beckham",
"457. David Duchovny",
"458. David Spade",
"459. Dax Shepard",
"460. Drew Barrymore",
"461. Eddie Murphy",
"462. Elijah Wood",
"463. Emma Stone",
"464. Emma Watson",
"465. Evan Peters",
"466. Seth MacFarlane",
"467. Idris Elba",
"468. Jack Black",
"469. James Franco",
"470. Jamie Foxx",
"471. Jason Bateman",
"472. Jason Statham",
"473. Jennifer Garner",
"474. Jennifer Lawrence",
"475. Jessica Chastain",
"476. John Goodman",
"477. John Leguizamo",
"478. John Malkovich",
"479. Jonah Hill",
"480. Joseph Gordon-Levitt",
"481. Josh Hutcherson",
"482. Justin Bieber",
"483. Justin Timberlake",
"484. Kate Winslet",
"485. Keanu Reeves",
"486. Kirsten Dunst",
"487. Kit Harington",
"488. Kristen Stewart",
"489. Kylie Jenner",
"490. Lady Gaga",
"491. Leonardo DiCaprio",
"492. Liam Neeson",
"493. Mahershala Ali",
"494. Margot Robbie",
"495. Matt Smith",
"496. Melissa McCarthy",
"497. Michael B. Jordan",
"498. Mindy Kaling",
"499. Naomi Watts",
"500. Natalie Portman",
"501. Neil Patrick Harris",
"502. Nick Jonas",
"503. Nicole Kidman",
"504. Orlando Bloom",
"505. Owen Wilson",
"506. Paul Giamatti",
"507. Penelope Cruz",
"508. Reese Witherspoon",
"509. Robert De Niro",
"510. Robert Downey Jr.",
"511. Roger Federer",
"512. Rooney Mara",
"513. Salma Hayek",
"514. Seth Rogan",
"515. Shia LaBeouf",
"516. Sophie Turner",
"517. Steve Buscemi",
"518. Steven Spielberg",
"519. Taylor Lautner",
"520. Tina Fey",
"521. Tom Cruise",
"522. Viola Davis",
"523. Will Smith",
"524. Zac Efron",
"525. Zooey Deschanel",
"526. Jennifer Aniston",
"527. Jennifer Lawrence",
"528. Jessica Alba",
"529. Jessica Simpson",
"530. Justin Bieber",
"531. Justin Timberlake",
"532. Kendall Jenner",
"533. Kim Kardashian",
"534. Kylie Jenner",
"535. Lady Gaga",
"536. Leonardo DiCaprio",
"537. Lindsey Vonn",
"538. Madonna",
"539. Mariah Carey",
"540. Megan Fox",
"542. Michelle Obama",
"543. Miley Cyrus",
"544. Naomi Campbell",
"545. Naomi Watts",
"546. Natalie Portman",
"547. Neymar",
"548. Nicki Minaj",
"550. Peyton Manning",
"551. Rafael Nadal",
"552. Reese Witherspoon",
"554. Robert De Niro",
"555. Roger Federer",
"556. Ronaldo",
"557. Russell Westbrook",
"558. Ryan Gosling",
"559. Selena Gomez",
"560. Serena Williams",
"561. Shah Rukh Khan",
"562. Taylor Swift",
"563. Tiger Woods",
"564. Tom Brady",
"565. Tom Cruise",
"566. Tyler Perry",
"567. Venus Williams",
"568. Victoria Beckham",
"569. Virat Kohli",
"570. Will Smith",
"571. Yao Ming",
"572. Zachary Levi",
"573. Zooey Deschanel",
"574. Amy Poehler",
"575. Angelina Jolie",
"576. Beyonce",
"577. Brad Pitt",
"578. Cameron Diaz",
"579. Carey Mulligan",
"580. Carrie Underwood",
"581. Celine Dion",
"582. Channing Tatum",
"583. Charlize Theron",
"584. Christina Aguilera",
"585. Daniel Radcliffe",
"586. Dolly Parton",
"587. Drew Barrymore",
"588. Eddie Murphy",
"589. Ellen DeGeneres",
"590. Elton John",
"591. Eminem",
"592. Jennifer Aniston",
"593. Jennifer Lopez",
"594. Jessica Simpson",
"595. Jim Carrey",
"596. Jimmy Fallon",
"597. Joan Rivers",
"598. Joe Manganiello",
"599. John Goodman",
"600. Johnny Depp",
"601. Justin Bieber",
"602. Justin Timberlake",
"603. Katie Holmes",
"604. Kelly Clarkson",
"605. Kevin Bacon",
"606. Kevin Costner",
"607. Kristin Chenoweth",
"608. Kylie Jenner",
"609. Lady Gaga",
"610. Leonardo Dicaprio",
"611. LL Cool J",
"612. Madonna",
"613. Matthew McConaughey",
"614. Melissa McCarthy",
"615. Miley Cyrus",
"616. Morgan Freeman",
"617. Naomi Watts",
"618. Natalie Portman",
"619. Neil Patrick Harris",
"620. Nicki Minaj",
"621. Nicole Kidman",
"623. Reese Witherspoon",
"625. Robert De Niro",
"Jensen Ackles",
"Andre 3000",
"Penn Badgley",
"Simon Baker",
"Christian Bale",
"Eric Balfour",
"Eric Bana",
"Alex Band",
"Antonio Banderas",
"Ben Barnes",
"Tyson Beckford",
"David Beckham",
"Jason Behr",
"Jonathan Bennett",
"Dierks Bentley",
"Gael Garcia Bernal",
"Jon Bernthal",
"Wilson Bethel ",
"Justin Bieber",
"David Blaine",
"James Blake",
"Corbin Bleu",
"Orlando Bloom",
"Jon Bon Jovi",
"Asher Book",
"Raoul Bova",
"Marlon Brando",
"Adam Brody",
"Chris Brown",
"Austin Butler",
"Gerard Butler",
"Santiago Cabrera",
"Bobby Cannavale",
"Nick Cannon",
"Robert Carmine",
"Chris Carmack",
"Jim Caviezel",
"Henry Cavill",
"John Cena",
"Justin Chambers",
"David Charvet",
"Hayden Christensen",
"Eddie Cibrian",
"George Clooney",
"Ben Cohen",
"Dane Cook",
"Anderson Cooper",
"Dominic Cooper",
"Michael Copon",
"Chris Cornell",
"Chace Crawford",
"Darren Criss",
"Russell Crowe",
"Tom Cruise",
"Daddy Yankee",
"Matt Dallas",
"Matt Damon",
"Hugh Dancy",
"Jeremy Davison",
"James Dean",
"Benicio Del Toro",
"Patrick Dempsey",
"Johnny Depp",
"Charles Dera",
"Alexandre Despatie",
"Aaron Diaz",
"Leonardo Dicaprio",
"Vin Diesel",
"Matt Dillon",
"Juan Dominic ",
"Gary Dourdan",
"Drake",
"Andreas Drakenberg",
"Bryce Draper",
"George Dubovoi",
"Josh Duhamel",
"George Eads",
"Michael Ealy",
"Zac Efron",
"Elvis",
"Eminem",
"Michael Erwin",
"Chris Evans",
"Fabolous",
"Sean Faris",
"Evan Farmer",
"Colin Farrell",
"Oded Fehr",
"Tom Felton",
"Ralph Fiennes",
"Travis Fimmel",
"Trent Ford",
"Matthew Fox",
"Dave Franco",
"James Franco",
"Drew Fuller",
"David Fumero",
"Franky G",
"Adam Garcia",
"Andrew Garfield ",
"Troy Garity",
"Louis Garrel",
"Teddy Geiger",
"Reynaldo Gianecchini",
"Cam Gigandet ",
"Nicholas Gonzalez",
"Rick Gonzalez",
"Ryan Gosling",
"The Gotti Boys",
"Adrien Grenier",
"Ioan Gruffudd",
"Jake Gyllenhaal",
"Gale Harold",
"Josh Hartnett",
"Colton Haynes ",
"Garrett Hedlund",
"Josh Henderson",
"David Henrie",
"Jay Hernandez",
"Tyler Hilton",
"Emile Hirsch",
"Josh Holloway",
"Marques Houston",
"Kris Humphries",
"Charlie Hunnam",
"Enrique Iglesias",
"Hugh Jackman",
"Jonathan Jackson",
"Thomas Jane",
"Ben Jelen",
"Derek Jeter",
"Avan Jogia",
"Aaron Johnson",
"Ben Patrick Johnson",
"Dwayne Johnson",
"Rusty Joiner",
"Joe Jonas",
"Kevin Jonas",
"Nick Jonas ",
"Wesley Jonathan",
"Steve Jones",
"Takeshi Kaneshiro",
"Gabe Kapler",
"Jordan Kaye",
"Gregory Keith",
"Toby Keith",
"Wiz Khalifa",
"Amir Khan",
"David Kimmerle",
"Taylor Kitsch",
"Johnny Knoxville",
"Boris Kodjoe",
"Lenny Kravitz",
"Ashton Kutcher",
"Shia LaBeouf",
"Nick Lachey",
"Caleb Lane",
"Taylor Lautner",
"Jude Law",
"Ryan LeBar",
"Samuel Le Bihan",
"Heath Ledger",
"Jared Leto",
"Adam Levine",
"Jason Lewis",
"LL Cool J",
"Laurent Lucas ",
"Diego Luna",
"Kellan Lutz",
"Tobey Maguire",
"Rick Malambri",
"Rami Malek",
"Forbes March",
"Derek Marrocco",
"James Marsden",
"James Marsters",
"Ricky Martin",
"Olivier Martinez",
"Jesse McCartney",
"Matthew McConaughey",
"Neil McDonough ",
"Ewan McGregor",
"Joey McIntyre ",
"Julian McMahon",
"Johnny Messner",
"Jesse Metcalfe",
"Blake Michael",
"Frederic Michalak",
"Mika",
"Wentworth Miller",
"Sal Mineo",
"Jason Momoa",
"Christian Monzon",
"Shemar Moore",
"Carlos Moore",
"Matthew Morrison",
"Viggo Mortensen",
"Dermot Mulroney",
"Cillian Murphy",
"Chad Michael Murray",
"Nelly",
"Paul Newman",
"Joe Nichols",
"Amaury Nolasco",
"Dylan O'Brien",
"Omarion",
"Randy Orton",
"Clive Owen",
"Jared Padalecki",
"Hunter Parrish ",
"Jason Patric",
"Marcus Patrick ",
"Robert Pattinson",
"Sean Paul",
"Evan Peters",
"Alex Pettyfer",
"Ryan Phillippe",
"Joaquin Phoenix",
"River Phoenix",
"Chris Pine",
"Stefan Pinto",
"Romulo Pires",
"Brad Pitt",
"Michael Pitt",
"Raul Popa",
"Tyler Posey",
"Elvis Presley",
"Jason Priestley",
"Dominic Purcell",
"James Purefoy",
"Shawn Pyfrom",
"Sendhil Ramamurthy",
"Keanu Reeves",
"Steve Reeves",
"Simon Rex",
"Ryan Reynolds",
"Jonathan Rhys-Meyers",
"Patrick Ribbsaeter",
"Thiago Ribeiro ",
"Caco Ricci",
"Tyson Ritter",
"Andy Roddick",
"Adam Rodriguez",
"Cristiano Ronaldo",
"Kenzie Roth",
"Brandon Routh",
"Mark Ruffalo",
"Mark Salling ",
"Steve Sandvoss",
"Rodrigo Santoro",
"Alejo Sauras",
"Joseph Sayers",
"Marcus Schenkenberg",
"Dayton Schlosser ",
"Robert Schwartzman ",
"Seann William Scott ",
"Frank Sepe",
"David Shaver",
"Ryan Sheckler",
"Shinya",
"Clement Sibony",
"Will Smith",
"Ian Somerhalder",
"Trey Songz",
"Soulja Boy",
"Hal Sparks",
"Scott Speedman",
"Edward Speleers",
"Jason Statham",
"Benjamin Stone",
"Richie Stringini",
"George Stults",
"Steven Strait",
"Daniel Sunjata",
"David Sutcliffe",
"Channing Tatum",
"T.I.",
"Lucas Till ",
"Justin Timberlake",
"Adam Tock",
"Sonny Tong ",
"Stuart Townsend",
"Tyrese",
"Gaspard Ulliel",
"Karl Urban",
"Keith Urban",
"Brendon Urie",
"Usher",
"Wilmer Valderrama",
"Mark Valley",
"Drew Van Acker",
"Jean-Claude Van Damme",
"Mark Vanderloo",
"Mario Vasquez",
"Milo Ventimiglia",
"Eduardo Verastegui",
"Rafael Verga",
"Jason Wade",
"Mark Wahlberg",
"Matt Walch",
"Paul Walker",
"Denzel Washington",
"DeAndre Way",
"Tom Welling",
"Peter Wentz",
"Dominic West",
"Shane West",
"Pharrell Williams",
"Robbie Williams",
"Bruce Willis",
"Andreas Wilson",
"Jamie Wise",
"Ronnie Woo",
"Elijah Wood",
"Christian Yanik ",
"Will Young",
"Nick Youngquest ",
"Billy Zane",
"Kevin Zegers",
"Rob Zombie",
"Zac Efron",
"Zac Hanson",
"Zac Posen",
"Zachary Levi",
"Zachary Quinto",
"Zach Galifianakis",
"Bradley Cooper",
"Aaron Eckhart",
"Aaron Judge",
"Adam Brody",
"Adam Levine",
"Adam Sandler",
"Noah Centineo",
"Noah Schnapp",
"Finn Wolfhard",
"Jacob Tremblay",
"Jack Dylan Grazer",
"Robert Redford",
"Robert Pattinson",
"Dave Franco",
"Dave Bautista",
"James Franco",
"Zach Galifianakis",
"Will Ferrell",
"Jonah Hill",
"Beanie Feldstein",
"Jerry Seinfeld",
"Wayne Knight",
"John Goodman",
"James McAvoy",
"Al Pacino",
"Logan Lerman",
"Ben Stiller",
"George Clooney",
"Martin Freeman",
"Aziz Ansari",
"Jack Black",
"Elijah Wood",
"Jason Segel",
"Jason Schwartzman",
"Mark Wahlberg",
"Michael Cera",
"Michael Douglas",
"Michael Fassbender",
"Michael J. Fox",
"Michael Keaton",
"Michael Shannon",
"Martin Sheen",
"Michael Stuhlbarg",
"Danny McBride",
"Dustin Hoffman",
"Ed Helms",
"Woody Harrelson",
"Woody Allen",
"Johnny Galecki",
"Josh Hutcherson",
"Josh Radnor",
"Ken Jeong",
"Toby Jones",
"Nathan Fielder",
"Nick Offerman",
"Nick Kroll",
"Nathan Lane",
"Nick Frost",
"Nick Jonas",
"Frankie Muniz",
"David Schwimmer",
"David Spade",
"Dave Portnoy",
"BD Wong",
"Bill Hader",
"Bill Murray",
"Bill Nye",
"Jason Alexander",
"Jason Bateman",
"Seth Rogen",
"Seth Green",
"Steve Carell",
"Steve Buscemi",
"Steve Martin",
"Simon Helberg",
"Patton Oswalt",
"Paul Rudd",
"Paul Giamatti",
"Rob Schneider",
"Peter Dinklage",
"Warwick Davis",
"Will Arnett",
]

for name in famous_people :
    if ("." in name) :
        name = name[name.index(".")+2:]
    name = name.lower()
    try :
        if (not json_includes(name, "Webpage/data.json")) : #if data doesn't already exists
            write_data(name)
            print("Successfully fetched data for " + name)
            sleep(2)
        else : #if data already exists
            print("Data already exists for " + name)
    except ValueError :
        print("Error fetching data for " + name)
